# Generated by Django 5.1.5 on 2025-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('license1', models.TextField(primary_key=True, serialize=False)),
                ('device', models.TextField(null=True)),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('registered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
