# Generated by Django 5.1.5 on 2025-01-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensekey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='device',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
