# Generated by Django 5.1.5 on 2025-01-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensekey', '0002_alter_licensekey_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensekey',
            old_name='license1',
            new_name='license',
        ),
    ]
